[providers.age]
type = "age"
recipients = ["age1hastr47pzgu82hsydvq2m9xgargxyzfhcy3ks5atljwuhlsy5chs0lchhl"]

[secrets]
NATL_IBM_API_KEY= { description = "National Market API key", provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDK0dTVHA2VHVFZWlpQXBpVXJJSlViRFZlYVJlZit4djJQMjFwSUE1VGhNClFqdzU5RnA4d2sydVgyeWRUVXBrdGFqOTZvbjZOZnNOSmJodjc1UlhGbVUKLS0tIG5CYy81VklBWWdUbWFkN1N0YXdsNEVlQjBlZmJFd1lZNmhVZnYvM3FJRlEKRe65BpernydJCD5UtGiR0sg4o0OsnhEp5vQoCN8pCyAdAqxT98biyLV9zlW7dxIY2zd2UyQk3m5Hr5c/J6mB+87Vc2FO18d4o/Xu0Q==" }
DTS_IBM_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZy9jUm1IMURpMndXNkpibXArc0NBaThmU3hDTFIzZFcwWnROZ1Z5VVhRCmcwdGs1NW8rcGZ0cS9ZMWhTVzVoODN2amk2TXZaMVljakcxT2FRbUduYVkKLS0tIGJuMlc4UkdiV0V2MjJMWUdvWXBWNVRINmdSZ0VYREtNRm1DQzMzL0RvQ0EKbsLnFuTk8GuZ6fDwBN7Z/V6+ciRLvgmp1UWYir1ZbyPNVoorDJPryF07Ch6AaPkwzMDJEMSCB76+jaOkxVFJN+HzB1Ohx8DWATKGGw==" }
